version: '3.7'

services:
  django-server:
#    restart: always
    build:
      context: .
      dockerfile: ./docker/django-server/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: config.production
    expose:
      - "8000"
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app
      - "staticdata:/var/www/app/static/"
      - "/var/log/:/var/log/django-tutorial-guest-board/"
    command: bash -c "python manage.py collectstatic --clear --noinput && gunicorn config.wsgi -b 0.0.0.0:8000"
    container_name: server-django-tutorial-guest-board

  nginx:
#    restart: always
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - django-server
    volumes:
      - "./docker/nginx/:/etc/nginx/"
      - "staticdata:/var/www/static/"
    container_name: nginx-django-tutorial-guest-board

volumes:
  staticdata: